/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clase7frame;

import java.io.File;
import java.nio.file.FileSystems;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author dalejwtf
 */
public class GestionCliente extends javax.swing.JFrame {

    /**
     * Creates new form GestionCliente
     */
    public String[] DevolverProvincias() {
        ArrayList<String> l = new ArrayList<>();
        try {
            Scanner tugfa = new Scanner(new File("provincias.txt"));
            while (tugfa.hasNextLine()) {
                String cadena = tugfa.nextLine();
                ArrayList<String> x = new ArrayList<>(Arrays.asList(cadena.split("/n")));
                String a = x.get(0);
                l.add(a);
            }
            
        } catch (Exception e) {
        }
        String[] arrStrings = new String[l.size()];
        for (int i = 0; i < l.size(); i++) {
            arrStrings[i] = l.get(i);
        }
        return arrStrings;
    }
    
    public GestionCliente() {
        initComponents();
        cmbProvinciaResidencia.setModel(new DefaultComboBoxModel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnContenedor = new javax.swing.JPanel();
        lblDatosGenerales = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        lblNombres = new javax.swing.JLabel();
        jpnTrabajo = new javax.swing.JPanel();
        lblProvincia1 = new javax.swing.JLabel();
        lblCalle1 = new javax.swing.JLabel();
        lblCanton1 = new javax.swing.JLabel();
        lblNumeroResidencia1 = new javax.swing.JLabel();
        cmbProvinciaTrabajo = new javax.swing.JComboBox<>();
        txtCantonTrabajo = new javax.swing.JTextField();
        txtCalleTrabajo = new javax.swing.JTextField();
        txtNroResidenciaTrabajo = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jpnResidencia = new javax.swing.JPanel();
        lblProvincia2 = new javax.swing.JLabel();
        lblCalle2 = new javax.swing.JLabel();
        lblCanton2 = new javax.swing.JLabel();
        lblNumeroResidencia2 = new javax.swing.JLabel();
        cmbProvinciaResidencia = new javax.swing.JComboBox<>();
        txtCantonResidencia = new javax.swing.JTextField();
        txtCalleResidencia = new javax.swing.JTextField();
        txtNroResidenciaResidencia = new javax.swing.JTextField();
        jpnBotones = new javax.swing.JPanel();
        btnBuscar = new javax.swing.JToggleButton();
        btnNuevo = new javax.swing.JToggleButton();
        btnGuardar = new javax.swing.JToggleButton();
        btnSalir = new javax.swing.JToggleButton();
        btnEliminar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnContenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblDatosGenerales.setFont(new java.awt.Font("Noto Mono", 1, 18)); // NOI18N
        lblDatosGenerales.setText("Datos Personales");

        lblCedula.setText("Cédula:");

        lblApellidos.setText("Apellidos:");

        lblNombres.setText("Nombres:");

        jpnTrabajo.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar Trabajo"));

        lblProvincia1.setText("Provincia: ");

        lblCalle1.setText("Calle:");

        lblCanton1.setText("Cantón:");

        lblNumeroResidencia1.setText("Numero Residencia:");

        cmbProvinciaTrabajo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProvinciaTrabajo.setEnabled(false);
        cmbProvinciaTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvinciaTrabajoActionPerformed(evt);
            }
        });

        txtCantonTrabajo.setEnabled(false);

        txtCalleTrabajo.setEnabled(false);

        txtNroResidenciaTrabajo.setEnabled(false);
        txtNroResidenciaTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroResidenciaTrabajoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnTrabajoLayout = new javax.swing.GroupLayout(jpnTrabajo);
        jpnTrabajo.setLayout(jpnTrabajoLayout);
        jpnTrabajoLayout.setHorizontalGroup(
            jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrabajoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCalleTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnTrabajoLayout.createSequentialGroup()
                        .addGroup(jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProvincia1)
                            .addComponent(lblCanton1)
                            .addComponent(lblCalle1)
                            .addComponent(lblNumeroResidencia1))
                        .addGroup(jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnTrabajoLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(txtNroResidenciaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTrabajoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbProvinciaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCantonTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jpnTrabajoLayout.setVerticalGroup(
            jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrabajoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvincia1)
                    .addComponent(cmbProvinciaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCanton1)
                    .addComponent(txtCantonTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalleTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalle1))
                .addGap(14, 14, 14)
                .addGroup(jpnTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroResidenciaTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroResidencia1)))
        );

        txtApellidos.setEnabled(false);

        txtNombres.setEnabled(false);

        jpnResidencia.setBorder(javax.swing.BorderFactory.createTitledBorder("Lugar Residencia"));

        lblProvincia2.setText("Provincia: ");

        lblCalle2.setText("Calle:");

        lblCanton2.setText("Cantón:");

        lblNumeroResidencia2.setText("Numero Residencia:");

        cmbProvinciaResidencia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbProvinciaResidencia.setEnabled(false);
        cmbProvinciaResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProvinciaResidenciaActionPerformed(evt);
            }
        });

        txtCantonResidencia.setEnabled(false);

        txtCalleResidencia.setEnabled(false);

        txtNroResidenciaResidencia.setEnabled(false);
        txtNroResidenciaResidencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNroResidenciaResidenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnResidenciaLayout = new javax.swing.GroupLayout(jpnResidencia);
        jpnResidencia.setLayout(jpnResidenciaLayout);
        jpnResidenciaLayout.setHorizontalGroup(
            jpnResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnResidenciaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProvincia2)
                    .addComponent(lblCanton2)
                    .addComponent(lblCalle2)
                    .addComponent(lblNumeroResidencia2))
                .addGap(24, 24, 24)
                .addGroup(jpnResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbProvinciaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCalleResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNroResidenciaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantonResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jpnResidenciaLayout.setVerticalGroup(
            jpnResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnResidenciaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProvincia2)
                    .addComponent(cmbProvinciaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCanton2)
                    .addComponent(txtCantonResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCalleResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCalle2))
                .addGap(14, 14, 14)
                .addGroup(jpnResidenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNroResidenciaResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumeroResidencia2)))
        );

        jpnBotones.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnBuscar.setText("Buscar");

        btnNuevo.setText("Nuevo");
        btnNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNuevoMouseClicked(evt);
            }
        });
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);

        javax.swing.GroupLayout jpnBotonesLayout = new javax.swing.GroupLayout(jpnBotones);
        jpnBotones.setLayout(jpnBotonesLayout);
        jpnBotonesLayout.setHorizontalGroup(
            jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBotonesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jpnBotonesLayout.setVerticalGroup(
            jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBotonesLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jpnBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscar)
                    .addComponent(btnNuevo)
                    .addComponent(btnGuardar)
                    .addComponent(btnSalir)
                    .addComponent(btnEliminar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnContenedorLayout = new javax.swing.GroupLayout(jpnContenedor);
        jpnContenedor.setLayout(jpnContenedorLayout);
        jpnContenedorLayout.setHorizontalGroup(
            jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnContenedorLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnContenedorLayout.createSequentialGroup()
                        .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jpnContenedorLayout.createSequentialGroup()
                                .addComponent(lblNombres)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnContenedorLayout.createSequentialGroup()
                                .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblApellidos)
                                    .addComponent(lblCedula))
                                .addGap(31, 31, 31)
                                .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblDatosGenerales, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpnContenedorLayout.createSequentialGroup()
                        .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpnBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jpnContenedorLayout.createSequentialGroup()
                                .addComponent(jpnResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jpnTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(296, 296, 296))))
        );
        jpnContenedorLayout.setVerticalGroup(
            jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnContenedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDatosGenerales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jpnContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnTrabajo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpnResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNroResidenciaTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroResidenciaTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroResidenciaTrabajoActionPerformed

    private void txtNroResidenciaResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNroResidenciaResidenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNroResidenciaResidenciaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalirActionPerformed

    private void cmbProvinciaTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvinciaTrabajoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProvinciaTrabajoActionPerformed

    private void cmbProvinciaResidenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProvinciaResidenciaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbProvinciaResidenciaActionPerformed

    private void btnNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNuevoMouseClicked
        // TODO add your handling code here:
        this.txtApellidos.setEnabled(true);
        this.txtNombres.setEnabled(true);
        this.txtCalleResidencia.setEnabled(true);
        this.txtCantonResidencia.setEnabled(true);
        this.txtNroResidenciaResidencia.setEnabled(true);
        this.cmbProvinciaResidencia.setEnabled(true);
        this.btnGuardar.setEnabled(true);
        String[] s = this.DevolverProvincias();
        cmbProvinciaResidencia.setModel(new DefaultComboBoxModel(s));
        

    }//GEN-LAST:event_btnNuevoMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GestionCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JToggleButton btnEliminar;
    private javax.swing.JToggleButton btnGuardar;
    private javax.swing.JToggleButton btnNuevo;
    private javax.swing.JToggleButton btnSalir;
    private javax.swing.JComboBox<String> cmbProvinciaResidencia;
    private javax.swing.JComboBox<String> cmbProvinciaTrabajo;
    private javax.swing.JPanel jpnBotones;
    private javax.swing.JPanel jpnContenedor;
    private javax.swing.JPanel jpnResidencia;
    private javax.swing.JPanel jpnTrabajo;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCalle1;
    private javax.swing.JLabel lblCalle2;
    private javax.swing.JLabel lblCanton1;
    private javax.swing.JLabel lblCanton2;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblDatosGenerales;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JLabel lblNumeroResidencia1;
    private javax.swing.JLabel lblNumeroResidencia2;
    private javax.swing.JLabel lblProvincia1;
    private javax.swing.JLabel lblProvincia2;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCalleResidencia;
    private javax.swing.JTextField txtCalleTrabajo;
    private javax.swing.JTextField txtCantonResidencia;
    private javax.swing.JTextField txtCantonTrabajo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNroResidenciaResidencia;
    private javax.swing.JTextField txtNroResidenciaTrabajo;
    // End of variables declaration//GEN-END:variables
}
