/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpaempleado;

import Controladores.EmpleadoJpaController;
import Controladores.exceptions.NonexistentEntityException;
import Entidades.Empleado;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dalejwtf
 */
public class frmEmpleado extends javax.swing.JFrame {

    DefaultTableModel model;
    EmpleadoJpaController ControladorEmp = new EmpleadoJpaController();
    int selectedRow;

    /**
     * Creates new form frmEmpleado
     */
    public frmEmpleado() {
        initComponents();
        CrearTablaEmp();
        CargarInf();
    }

    private void CrearTablaEmp() {
        Object tblCol[] = {"Id", "Cedula", "Apellidos", "Nombres", "Edad", "Sueldo"};
        model = new DefaultTableModel(null, tblCol);
        jtblEmp.setModel(model);
    }

    private void CargarInf() {
        try {
            List<Empleado> listEmp = ControladorEmp.findEmpleadoEntities();
            DefaultTableModel model = (DefaultTableModel) jtblEmp.getModel();
            model.setRowCount(0);
            jtblEmp = new JTable(model);
            Object rowData[] = new Object[6];
            for (int i = 0; i < listEmp.size(); i++) {
                rowData[0] = listEmp.get(i).getIdEmpleado();
                rowData[1] = listEmp.get(i).getCedula();
                rowData[2] = listEmp.get(i).getApellidos();
                rowData[3] = listEmp.get(i).getNombres();
                rowData[4] = listEmp.get(i).getEdad();
                rowData[5] = listEmp.get(i).getSueldo();
                model.addRow(rowData);

            }
        } catch (Exception e) {
        }

    }

    public void SeleccionarEmpleado() {

        int fila = jtblEmp.getSelectedRow();
        jtxtfCedula.setText(jtblEmp.getModel().getValueAt(fila, 1).toString());
        jtxtfApellidos.setText(jtblEmp.getModel().getValueAt(fila, 2).toString());
        jtxtfNombres.setText(jtblEmp.getModel().getValueAt(fila, 3).toString());
        jtxtfEdad.setText(jtblEmp.getModel().getValueAt(fila, 4).toString());
        jtxtfSueldo.setText(jtblEmp.getModel().getValueAt(fila, 5).toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEmp = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtxtfCedula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtfSueldo = new javax.swing.JTextField();
        jtxtfEdad = new javax.swing.JTextField();
        jtxtfNombres = new javax.swing.JTextField();
        jtxtfApellidos = new javax.swing.JTextField();
        jbtnAdicionar = new javax.swing.JButton();
        jbtnEliminar = new javax.swing.JButton();
        jbtnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtblEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblEmp);

        jLabel1.setText("Cédula:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("Nombres:");

        jLabel4.setText("Edad:");

        jLabel5.setText("Sueldo:");

        jtxtfNombres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfNombresActionPerformed(evt);
            }
        });

        jtxtfApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfApellidosActionPerformed(evt);
            }
        });

        jbtnAdicionar.setText("Adicionar");
        jbtnAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnAdicionarMouseClicked(evt);
            }
        });

        jbtnEliminar.setText("Eliminar");
        jbtnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbtnEliminarMouseClicked(evt);
            }
        });

        jbtnModificar.setText("Modificar");
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtfCedula)
                            .addComponent(jtxtfApellidos)
                            .addComponent(jtxtfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtxtfSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtnModificar, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(22, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxtfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jtxtfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtxtfSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnAdicionar)
                        .addGap(31, 31, 31)
                        .addComponent(jbtnEliminar)
                        .addGap(29, 29, 29)
                        .addComponent(jbtnModificar)
                        .addGap(24, 24, 24)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtfNombresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfNombresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfNombresActionPerformed

    private void jtxtfApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfApellidosActionPerformed

    private void jbtnAdicionarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnAdicionarMouseClicked

        Empleado emp = new Empleado();
        emp.setCedula(jtxtfCedula.getText());
        emp.setApellidos(jtxtfApellidos.getText());
        emp.setNombres(jtxtfNombres.getText());
        emp.setEdad(Integer.parseInt(jtxtfEdad.getText()));
        emp.setSueldo(Long.parseLong(jtxtfSueldo.getText()));
        ControladorEmp.create(emp);
        JOptionPane.showMessageDialog(null, "Datos Adicionados");
        CargarInf();

    }//GEN-LAST:event_jbtnAdicionarMouseClicked

    private void jbtnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtnEliminarMouseClicked

        int aux = (Integer) jtblEmp.getValueAt(jtblEmp.getSelectedRow(), 0);

        try {
            ControladorEmp.destroy(aux);
        } catch (NonexistentEntityException ex) {
            Logger.getLogger(frmEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(null, "Datos Eliminados");
        CargarInf();
    }//GEN-LAST:event_jbtnEliminarMouseClicked

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        try {
            Empleado emp = new Empleado();
            int aux = (Integer) jtblEmp.getValueAt(jtblEmp.getSelectedRow(), 0);
            emp.setIdEmpleado(aux);
            emp.setCedula(jtxtfCedula.getText());
            emp.setApellidos(jtxtfApellidos.getText());
            emp.setNombres(jtxtfNombres.getText());
            emp.setEdad(Integer.parseInt(jtxtfEdad.getText()));
            emp.setSueldo(Long.parseLong(jtxtfSueldo.getText()));
            ControladorEmp.edit(emp);
            JOptionPane.showMessageDialog(null, "Datos Modificados");
            CargarInf();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jbtnModificarActionPerformed

    private void jtblEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblEmpMouseClicked
        // TODO add your handling code here:
        selectedRow = jtblEmp.rowAtPoint(evt.getPoint());
        jtxtfCedula.setText(jtblEmp.getModel().getValueAt(selectedRow, 1).toString());
        jtxtfApellidos.setText(jtblEmp.getModel().getValueAt(selectedRow, 2).toString());
        jtxtfNombres.setText(jtblEmp.getModel().getValueAt(selectedRow, 3).toString());
        jtxtfEdad.setText(jtblEmp.getModel().getValueAt(selectedRow, 4).toString());
        jtxtfSueldo.setText(jtblEmp.getModel().getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_jtblEmpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnAdicionar;
    private javax.swing.JButton jbtnEliminar;
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JTable jtblEmp;
    private javax.swing.JTextField jtxtfApellidos;
    private javax.swing.JTextField jtxtfCedula;
    private javax.swing.JTextField jtxtfEdad;
    private javax.swing.JTextField jtxtfNombres;
    private javax.swing.JTextField jtxtfSueldo;
    // End of variables declaration//GEN-END:variables
}
